### PR TITLE
Retry logic for closed connections

### PR DESCRIPTION
**Pull request by cataliniatan**
The Atrea unit was not accessible anymore after a couple of minutes due to the closure of the websockets connections.

### CODE REVIEW

**Comment by xbezdick** [comment]
First thanks for the patch sent.

Can you enable debugging and "grep homeassistant.components.automation.recirculation homeassistant/home-assistant.log" provide this log? I think there shouldn't be need for reconnects in few minutes.

Also I think previous commit got mixed into this one with websockets include so please remove that file from this pullrequest?
Aaand I think websockets include is completely unnecessary in sensors so maybe we should be removing it. The websockets logic should be only in _init_.py

**Comment by cataliniatan** [comment]
I am new to HA and I am running these tests in a dev environment on my laptop .  
I attached the relevant debug logs for the custom_component, HA logs do not contain anything on automation.recirculation so if these are needed I may need to look further into it.

After applying the fix proposed, the ventilation controls are responding fine even after a couple of hours; however, I noticed the sensor data does not update after a couple of minutes (which Is not related to this change but I would need to look into anyway).
[custom_component_aatrea.log](https://github.com/user-attachments/files/17184736/custom_component_aatrea.log)

If you are not seeing this issue, I am thinking it may be due to my network setup. I have a session based firewall between HA and the Atrea unit which may be ending the session. 
Thanks for your work.

**Comment by xbezdick** [comment]
Also please use branch issue_7 to test my change.

**Comment by cataliniatan** [comment]
After the most recent changes the sensor data does not freeze anymore:
Screenshot 2024-10-07 at 11 41 32

**Comment by xbezdick** [comment]
Thanks, I rebased your code and pulled it in. I also added retry code.

**Comment by xbezdick** [comment]
Note I reproduced only by powering off the unit, are you sure it's not restarting on your side?

**Comment by cataliniatan** [comment]
Let me check if I pushed the latest changes I made, my unit has been stable for the past 3 weeks.

**Comment by cataliniatan** [comment]
I checked by disabling the network interface and indeed, it's not reconnecting. I will have to look into it.

**Comment by cataliniatan** [comment]
actually, it recovered automatically after 10 minutes, the only thing I did was to start a debug :
image

**Pull request closed without merging**
